A:bind_vec2
B:bind_vec3
C:bind_vec4
scene_node
AA
BB
CC

C(bind_vec4)
  B(bind_vec3)
    A(bind_vec2)
      base(scene_node)

C(bind_vec4)
  B(bind_vec3)
    A(bind_vec2)
      base(scene_node)
        D(scene_node)

C(bind_vec4)
  B(bind_vec3)
    A(bind_vec2)
      base(scene_node)
        D(scene_node)
    E(scene_node)

C(bind_vec4)
  B(bind_vec3)
    A(bind_vec2)
      base(scene_node)
        D(scene_node)

2
3
4
---
C(bind_vec3)
  B(bind_vec2)
    A(scene_node)
      C(bind_vec3) [cycle]

A(scene_node)
  C(bind_vec3)
    B(bind_vec2)
      A(scene_node) [cycle]

B(bind_vec2)
  A(scene_node)
    C(bind_vec3)
      B(bind_vec2) [cycle]

C(bind_vec3)
  B(bind_vec2)
    A(scene_node)
      C(bind_vec3) [cycle]

1
2
3
1
2
3

2
3
