1
root
2
root
  child1
  child2
3
root
  child1
  child2
  child3
4
root
  child1
  child2
  child3
  child2
  child1
5
root
  child2
  child3
  child2
  child1
6
root
  child2
  child3
  child2
  child3
7
root
  child1
  child2
  child3
  child2
  child3
8
root
9
root
  child1
  child2
  child3
10
root
  child1
    child1 [cycle]
  child2
  child3
11
root
  child1
    child1 [cycle]
  child2
    child1
      child1 [cycle]
  child3
12
root
  child1
    child2
      child3
        child2 [cycle]
        child1 [cycle]
  child2
    child3
      child2 [cycle]
      child1
        child2 [cycle]
  child3
    child2
      child3 [cycle]
    child1
      child2
        child3 [cycle]
13
root
  child1
  child2
    child3
      child2 [cycle]
      child1
  child3
    child2
      child3 [cycle]
    child1
14
A
  B
    C
15
A
  B
    C
      D
16
A
  B
    C
    D
    E
17
A
  B
    C
      F
    D
      F
    E
      F
18
A
  B
    C
    C
19
A
  C
    C [cycle]
    C [cycle]
20
A
  C
    C [cycle]
  C
    C [cycle]
21
A
  C
    B
  C
    B
22
A
  C
    B
      C [cycle]
      C [cycle]
  C
    B
      C [cycle]
      C [cycle]
23
A
  B
    C
      D
  E
    F
24
A
  B
    C
      D
        G
  E
    F
      G
25
A
  B
    C
      D
26
A
  B
    C
    D
