#!/bin/sh
set -e
mkdir amulet.iconset
sips -z 16 16     amulet_icon_1024_alpha.png --out amulet.iconset/icon_16x16.png
sips -z 32 32     amulet_icon_1024_alpha.png --out amulet.iconset/icon_16x16@2x.png
sips -z 32 32     amulet_icon_1024_alpha.png --out amulet.iconset/icon_32x32.png
sips -z 64 64     amulet_icon_1024_alpha.png --out amulet.iconset/icon_32x32@2x.png
sips -z 128 128   amulet_icon_1024_alpha.png --out amulet.iconset/icon_128x128.png
sips -z 256 256   amulet_icon_1024_alpha.png --out amulet.iconset/icon_128x128@2x.png
sips -z 256 256   amulet_icon_1024_alpha.png --out amulet.iconset/icon_256x256.png
sips -z 512 512   amulet_icon_1024_alpha.png --out amulet.iconset/icon_256x256@2x.png
sips -z 512 512   amulet_icon_1024_alpha.png --out amulet.iconset/icon_512x512.png
cp amulet_icon_1024_alpha.png amulet.iconset/icon_512x512@2x.png
iconutil -c icns amulet.iconset
rm -rf amulet.iconset
