win = am.window{title = "Mouse",
    clear_color = vec4(1)}

face_img = [[
........BBBBBBBBBB.................
.....BBBBBBBBBBBBBBBBBBB...........
...BBBBBBBBBBBBBBBBBBBBBBBBB.......
..BBBBBBBBBBBBBBBBBBBBBBBBBBB......
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBB.....
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB....
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB...
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB...
BBBBKKKKKKKKBBBBBBBBBBBBBBBBBBBB...
BBBBBKBKBKBKBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBCBBBBBBBKKKKKKKKBBBBBBB
BBBBBBBBBBBCBBBBBBBBBKBKBKBKBBBBBBB
BBBBBBBBBBBCBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBCCBBBBCBBBBBBBBBBBBBBBBBB
BBBBBBBBBBCBBBBCCCCBBBBBBBBBBBBBBBB
BBBBBBBBBCCBBBBBBBCBBBBBBBBBBBBBBBB
BBBBBBBBBCBBBBBBBCCBBBBBBBBBBBBBB..
BBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBB..
BBBBRRRRRRRRRRRRRRRRRRRRRRRRBBBBB..
BBBBRKKWKWKWWKWWWKWKWKWKWKWRBBBBB..
BBBBRKKKKKKKKKKKKKKKKKKKKKKRBBBBB..
BBBBRWKWKWKWWKWWKWWKWWWKWKWRBBBBB..
BBBBRRRRRRRRRRRRRRRRRRRRRRRRBBBBB..
..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB...
...BBBBBBBBBBBBBBBBBBBBBBBBBBBB....
......BBBBBBBBBBBBBBBBBBBBBBBB.....
]]

eye_img = [[
.K.K.K.K.
.KKKKKKK.
KYYYYYYYK
KYYYRRYYK
KYYRRRRYK
KYYRWRRYK
KYYYRRYYK
KYYYYYYYK
.KKKKKKK.
.K.K.K.K.
]]

face = am.translate(0, 0) ^ am.scale(4) ^ {
    am.sprite(face_img)
    ,
    am.translate(-9, 4):tag"left_eye"
    ^ am.sprite(eye_img)
    ,
    am.translate(6, 3):tag"right_eye"
    ^ am.sprite(eye_img)
    ,
}

face"left_eye".hidden = true
face"right_eye".hidden = true

face:action(function()
    face.position2d = win:mouse_position()
    face"left_eye".hidden = not win:mouse_down"left"
    face"right_eye".hidden = not win:mouse_down"right"
end)

win.scene = face
