AM_GLPROC(void        ,glActiveTexture ,(GLenum texture))
AM_GLPROC(void        ,glAttachShader ,(GLuint program, GLuint shader))
AM_GLPROC(void        ,glBindAttribLocation ,(GLuint program, GLuint index, const GLchar* name))
AM_GLPROC(void        ,glBindBuffer ,(GLenum target, GLuint buffer))
AM_GLPROC(void        ,glBindFramebuffer ,(GLenum target, GLuint framebuffer))
AM_GLPROC(void        ,glBindRenderbuffer ,(GLenum target, GLuint renderbuffer))
AM_GLPROC(void        ,glBindTexture ,(GLenum target, GLuint texture))
AM_GLPROC(void        ,glBlendColor ,(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha))
AM_GLPROC(void        ,glBlendEquation ,( GLenum mode ))
AM_GLPROC(void        ,glBlendEquationSeparate ,(GLenum modeRGB, GLenum modeAlpha))
AM_GLPROC(void        ,glBlendFunc ,(GLenum sfactor, GLenum dfactor))
AM_GLPROC(void        ,glBlendFuncSeparate ,(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha))
AM_GLPROC(void        ,glBufferData ,(GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage))
AM_GLPROC(void        ,glBufferSubData ,(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data))
AM_GLPROC(GLenum      ,glCheckFramebufferStatus ,(GLenum target))
AM_GLPROC(void        ,glClear ,(GLbitfield mask))
AM_GLPROC(void        ,glClearColor ,(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha))
AM_GLPROC(void        ,glClearDepthf ,(GLclampf depth))
AM_GLPROC(void        ,glClearStencil ,(GLint s))
AM_GLPROC(void        ,glColorMask ,(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
AM_GLPROC(void        ,glCompileShader ,(GLuint shader))
AM_GLPROC(void        ,glCompressedTexImage2D ,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data))
AM_GLPROC(void        ,glCompressedTexSubImage2D ,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data))
AM_GLPROC(void        ,glCopyTexImage2D ,(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
AM_GLPROC(void        ,glCopyTexSubImage2D ,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
AM_GLPROC(GLuint      ,glCreateProgram ,(void))
AM_GLPROC(GLuint      ,glCreateShader ,(GLenum type))
AM_GLPROC(void        ,glCullFace ,(GLenum mode))
AM_GLPROC(void        ,glDeleteBuffers ,(GLsizei n, const GLuint* buffers))
AM_GLPROC(void        ,glDeleteFramebuffers ,(GLsizei n, const GLuint* framebuffers))
AM_GLPROC(void        ,glDeleteProgram ,(GLuint program))
AM_GLPROC(void        ,glDeleteRenderbuffers ,(GLsizei n, const GLuint* renderbuffers))
AM_GLPROC(void        ,glDeleteShader ,(GLuint shader))
AM_GLPROC(void        ,glDeleteTextures ,(GLsizei n, const GLuint* textures))
AM_GLPROC(void        ,glDepthFunc ,(GLenum func))
AM_GLPROC(void        ,glDepthMask ,(GLboolean flag))
AM_GLPROC(void        ,glDepthRangef ,(GLclampf zNear, GLclampf zFar))
AM_GLPROC(void        ,glDetachShader ,(GLuint program, GLuint shader))
AM_GLPROC(void        ,glDisable ,(GLenum cap))
AM_GLPROC(void        ,glDisableVertexAttribArray ,(GLuint index))
AM_GLPROC(void        ,glDrawArrays ,(GLenum mode, GLint first, GLsizei count))
AM_GLPROC(void        ,glDrawElements ,(GLenum mode, GLsizei count, GLenum type, const GLvoid* indices))
AM_GLPROC(void        ,glEnable ,(GLenum cap))
AM_GLPROC(void        ,glEnableVertexAttribArray ,(GLuint index))
AM_GLPROC(void        ,glFinish ,(void))
AM_GLPROC(void        ,glFlush ,(void))
AM_GLPROC(void        ,glFramebufferRenderbuffer ,(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
AM_GLPROC(void        ,glFramebufferTexture2D ,(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
AM_GLPROC(void        ,glFrontFace ,(GLenum mode))
AM_GLPROC(void        ,glGenBuffers ,(GLsizei n, GLuint* buffers))
AM_GLPROC(void        ,glGenerateMipmap ,(GLenum target))
AM_GLPROC(void        ,glGenFramebuffers ,(GLsizei n, GLuint* framebuffers))
AM_GLPROC(void        ,glGenRenderbuffers ,(GLsizei n, GLuint* renderbuffers))
AM_GLPROC(void        ,glGenTextures ,(GLsizei n, GLuint* textures))
AM_GLPROC(void        ,glGetActiveAttrib ,(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name))
AM_GLPROC(void        ,glGetActiveUniform ,(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name))
AM_GLPROC(void        ,glGetAttachedShaders ,(GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders))
AM_GLPROC(int         ,glGetAttribLocation ,(GLuint program, const GLchar* name))
AM_GLPROC(void        ,glGetBooleanv ,(GLenum pname, GLboolean* params))
AM_GLPROC(void        ,glGetBufferParameteriv ,(GLenum target, GLenum pname, GLint* params))
AM_GLPROC(GLenum      ,glGetError ,(void))
AM_GLPROC(void        ,glGetFloatv ,(GLenum pname, GLfloat* params))
AM_GLPROC(void        ,glGetFramebufferAttachmentParameteriv ,(GLenum target, GLenum attachment, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetIntegerv ,(GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetProgramiv ,(GLuint program, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetProgramInfoLog ,(GLuint program, GLsizei bufsize, GLsizei* length, GLchar* infolog))
AM_GLPROC(void        ,glGetRenderbufferParameteriv ,(GLenum target, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetShaderiv ,(GLuint shader, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetShaderInfoLog ,(GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* infolog))
AM_GLPROC(void        ,glGetShaderPrecisionFormat ,(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision))
AM_GLPROC(void        ,glGetShaderSource ,(GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* source))
AM_GLPROC(const GLubyte*, glGetString ,(GLenum name))
AM_GLPROC(void        ,glGetTexParameterfv ,(GLenum target, GLenum pname, GLfloat* params))
AM_GLPROC(void        ,glGetTexParameteriv ,(GLenum target, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetUniformfv ,(GLuint program, GLint location, GLfloat* params))
AM_GLPROC(void        ,glGetUniformiv ,(GLuint program, GLint location, GLint* params))
AM_GLPROC(int         ,glGetUniformLocation ,(GLuint program, const GLchar* name))
AM_GLPROC(void        ,glGetVertexAttribfv ,(GLuint index, GLenum pname, GLfloat* params))
AM_GLPROC(void        ,glGetVertexAttribiv ,(GLuint index, GLenum pname, GLint* params))
AM_GLPROC(void        ,glGetVertexAttribPointerv ,(GLuint index, GLenum pname, GLvoid** pointer))
AM_GLPROC(void        ,glHint ,(GLenum target, GLenum mode))
AM_GLPROC(GLboolean   ,glIsBuffer ,(GLuint buffer))
AM_GLPROC(GLboolean   ,glIsEnabled ,(GLenum cap))
AM_GLPROC(GLboolean   ,glIsFramebuffer ,(GLuint framebuffer))
AM_GLPROC(GLboolean   ,glIsProgram ,(GLuint program))
AM_GLPROC(GLboolean   ,glIsRenderbuffer ,(GLuint renderbuffer))
AM_GLPROC(GLboolean   ,glIsShader ,(GLuint shader))
AM_GLPROC(GLboolean   ,glIsTexture ,(GLuint texture))
AM_GLPROC(void        ,glLineWidth ,(GLfloat width))
AM_GLPROC(void        ,glLinkProgram ,(GLuint program))
AM_GLPROC(void        ,glPixelStorei ,(GLenum pname, GLint param))
AM_GLPROC(void        ,glPolygonOffset ,(GLfloat factor, GLfloat units))
AM_GLPROC(void        ,glReadPixels ,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels))
AM_GLPROC(void        ,glReleaseShaderCompiler ,(void))
AM_GLPROC(void        ,glRenderbufferStorage ,(GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
AM_GLPROC(void        ,glSampleCoverage ,(GLclampf value, GLboolean invert))
AM_GLPROC(void        ,glScissor ,(GLint x, GLint y, GLsizei width, GLsizei height))
AM_GLPROC(void        ,glShaderBinary ,(GLsizei n, const GLuint* shaders, GLenum binaryformat, const GLvoid* binary, GLsizei length))
AM_GLPROC(void        ,glShaderSource ,(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length))
AM_GLPROC(void        ,glStencilFunc ,(GLenum func, GLint ref, GLuint mask))
AM_GLPROC(void        ,glStencilFuncSeparate ,(GLenum face, GLenum func, GLint ref, GLuint mask))
AM_GLPROC(void        ,glStencilMask ,(GLuint mask))
AM_GLPROC(void        ,glStencilMaskSeparate ,(GLenum face, GLuint mask))
AM_GLPROC(void        ,glStencilOp ,(GLenum fail, GLenum zfail, GLenum zpass))
AM_GLPROC(void        ,glStencilOpSeparate ,(GLenum face, GLenum fail, GLenum zfail, GLenum zpass))
AM_GLPROC(void        ,glTexImage2D ,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels))
AM_GLPROC(void        ,glTexParameterf ,(GLenum target, GLenum pname, GLfloat param))
AM_GLPROC(void        ,glTexParameterfv ,(GLenum target, GLenum pname, const GLfloat* params))
AM_GLPROC(void        ,glTexParameteri ,(GLenum target, GLenum pname, GLint param))
AM_GLPROC(void        ,glTexParameteriv ,(GLenum target, GLenum pname, const GLint* params))
AM_GLPROC(void        ,glTexSubImage2D ,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels))
AM_GLPROC(void        ,glUniform1f ,(GLint location, GLfloat x))
AM_GLPROC(void        ,glUniform1fv ,(GLint location, GLsizei count, const GLfloat* v))
AM_GLPROC(void        ,glUniform1i ,(GLint location, GLint x))
AM_GLPROC(void        ,glUniform1iv ,(GLint location, GLsizei count, const GLint* v))
AM_GLPROC(void        ,glUniform2f ,(GLint location, GLfloat x, GLfloat y))
AM_GLPROC(void        ,glUniform2fv ,(GLint location, GLsizei count, const GLfloat* v))
AM_GLPROC(void        ,glUniform2i ,(GLint location, GLint x, GLint y))
AM_GLPROC(void        ,glUniform2iv ,(GLint location, GLsizei count, const GLint* v))
AM_GLPROC(void        ,glUniform3f ,(GLint location, GLfloat x, GLfloat y, GLfloat z))
AM_GLPROC(void        ,glUniform3fv ,(GLint location, GLsizei count, const GLfloat* v))
AM_GLPROC(void        ,glUniform3i ,(GLint location, GLint x, GLint y, GLint z))
AM_GLPROC(void        ,glUniform3iv ,(GLint location, GLsizei count, const GLint* v))
AM_GLPROC(void        ,glUniform4f ,(GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
AM_GLPROC(void        ,glUniform4fv ,(GLint location, GLsizei count, const GLfloat* v))
AM_GLPROC(void        ,glUniform4i ,(GLint location, GLint x, GLint y, GLint z, GLint w))
AM_GLPROC(void        ,glUniform4iv ,(GLint location, GLsizei count, const GLint* v))
AM_GLPROC(void        ,glUniformMatrix2fv ,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
AM_GLPROC(void        ,glUniformMatrix3fv ,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
AM_GLPROC(void        ,glUniformMatrix4fv ,(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value))
AM_GLPROC(void        ,glUseProgram ,(GLuint program))
AM_GLPROC(void        ,glValidateProgram ,(GLuint program))
AM_GLPROC(void        ,glVertexAttrib1f ,(GLuint indx, GLfloat x))
AM_GLPROC(void        ,glVertexAttrib1fv ,(GLuint indx, const GLfloat* values))
AM_GLPROC(void        ,glVertexAttrib2f ,(GLuint indx, GLfloat x, GLfloat y))
AM_GLPROC(void        ,glVertexAttrib2fv ,(GLuint indx, const GLfloat* values))
AM_GLPROC(void        ,glVertexAttrib3f ,(GLuint indx, GLfloat x, GLfloat y, GLfloat z))
AM_GLPROC(void        ,glVertexAttrib3fv ,(GLuint indx, const GLfloat* values))
AM_GLPROC(void        ,glVertexAttrib4f ,(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
AM_GLPROC(void        ,glVertexAttrib4fv ,(GLuint indx, const GLfloat* values))
AM_GLPROC(void        ,glVertexAttribPointer ,(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* ptr))
AM_GLPROC(void        ,glViewport ,(GLint x, GLint y, GLsizei width, GLsizei height))
