// This file is generated by tools/gen_mathv.lua
void am_open_mathv_module(lua_State *L);
int am_mathv_add(lua_State *L);
int am_mathv_sub(lua_State *L);
int am_mathv_mul(lua_State *L);
int am_mathv_div(lua_State *L);
int am_mathv_mod(lua_State *L);
int am_mathv_pow(lua_State *L);
int am_mathv_unm(lua_State *L);
int am_mathv_sin(lua_State *L);
int am_mathv_dot(lua_State *L);
int am_mathv_vec4(lua_State *L);
