#define AM_RESERVED_REFS_START 10

typedef enum {
    AM_PARAM_NAME_STRING_TABLE = AM_RESERVED_REFS_START,

    AM_WINDOW_TABLE,

    AM_MT_WINDOW,
    AM_MT_NODE,
    AM_MT_PROGRAM,

    AM_MT_BUFFER,
    AM_MT_BUFFER_VIEW,
    AM_MT_BUFFER_VIEW_FLOAT,
    AM_MT_BUFFER_VIEW_FLOAT_VEC2,
    AM_MT_BUFFER_VIEW_FLOAT_VEC3,
    AM_MT_BUFFER_VIEW_FLOAT_VEC4,
    AM_MT_BUFFER_VIEW_BYTE,
    AM_MT_BUFFER_VIEW_BYTE_VEC2,
    AM_MT_BUFFER_VIEW_BYTE_VEC3,
    AM_MT_BUFFER_VIEW_BYTE_VEC4,
    AM_MT_BUFFER_VIEW_UNSIGNED_BYTE,
    AM_MT_BUFFER_VIEW_UNSIGNED_BYTE_VEC2,
    AM_MT_BUFFER_VIEW_UNSIGNED_BYTE_VEC3,
    AM_MT_BUFFER_VIEW_UNSIGNED_BYTE_VEC4,
    AM_MT_BUFFER_VIEW_SHORT,
    AM_MT_BUFFER_VIEW_SHORT_VEC2,
    AM_MT_BUFFER_VIEW_SHORT_VEC3,
    AM_MT_BUFFER_VIEW_SHORT_VEC4,
    AM_MT_BUFFER_VIEW_UNSIGNED_SHORT,
    AM_MT_BUFFER_VIEW_UNSIGNED_SHORT_VEC2,
    AM_MT_BUFFER_VIEW_UNSIGNED_SHORT_VEC3,
    AM_MT_BUFFER_VIEW_UNSIGNED_SHORT_VEC4,

    AM_MT_VEC2,
    AM_MT_VEC3,
    AM_MT_VEC4,
    AM_MT_MAT2,
    AM_MT_MAT3,
    AM_MT_MAT4,

    AM_RESERVED_REFS_END
} am_reserved_refs;
