on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install X11
        run: sudo apt install libx11-dev
      - name: Build linux64.release.lua51
        run: make TARGET=linux64.release LUAVM=lua51
  build_macos:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build osx.release.lua51
        run: make TARGET=osx.release     LUAVM=lua51
      - name: Build ios.release.lua51
        run: make TARGET=ios.release     LUAVM=lua51
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS
        uses: msys2/setup-msys2@v2
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - run: uname
      - name: Build msvc64.release.lua51
        run: make TARGET=msvc64.release LUAVM=lua51
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: amulet-builds-windows
          path: builds
          if-no-files-found: error
          retention-days: 1
          overwrite: true
  distros:
    needs: [build_linux, build_macos, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download builds windows
        uses: actions/download-artifact@v4
        name: amulet-builds-windows
        merge-multiple: true
